### ISSUE TITLE
No data in output file (run lscraper from CLI)

### ISSUE THREAD

**Issue by alexander-mart** [ivbeg/lazyscraper#2]
```
lscraper extract --url "https://web.archive.org/" --xpath "//div[1]" --output output.txt

2022-04-06 21:43:05,755 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): web.archive.org:443
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host 'web.archive.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2022-04-06 21:43:07,833 - urllib3.connectionpool - DEBUG - https://web.archive.org:443 "GET / HTTP/1.1" 200 None

```

output.txt
```
_tag,class,id,_text
```

**Comment by ivbeg** [comment]
Fixed. It was silly bug during local file processing implementation( 

Rusult should be like this
--
_tag,class,id,_text

div,ia-banners,,"Due to a planned power outage on Friday, 1/14, between 8am-1pm PST, some services may be impacted."

div,ia-banner hidden outage-2022-01-14,,"Due to a planned power outage on Friday, 1/14, between 8am-1pm PST, some services may be impacted."

div,topnav style-scope ia-topnav,,"Internet Archive logo A line drawing of the Internet Archive headquarters building façade. Search icon An illustration of a magnifying glass. Search icon An illustration of a magnifying glass. Upload icon An illustration of a horizontal line over an up pointing arrow. Upload User icon An illustration of a person's head and chest. Sign up | Log in Web icon An illustration of a computer application window Wayback Machine Texts icon An illustration of an open book. Books Video icon An illustration of two cells of a film strip. Video Audio icon An illustration of an audio speaker. Audio Software icon An illustration of a 3.5"" floppy disk. Software Images icon An illustration of two photographs. Images Donate icon An illustration of a heart shape Donate Ellipses icon An illustration of text ellipses. More Hamburger icon An icon used to represent a menu that can be toggled by interacting with this icon."

div,search-activated fade-in search-inactive style-scope nav-search,,Search icon An illustration of a magnifying glass.

div,user-info style-scope primary-nav,,User icon An illustration of a person's head and chest. Sign up | Log in

div,logged-out-toolbar style-scope login-button,,User icon An illustration of a person's head and chest. Sign up | Log in

div,menu-group style-scope media-menu,,"Web icon An illustration of a computer application window Wayback Machine Texts icon An illustration of an open book. Books Video icon An illustration of two cells of a film strip. Video Audio icon An illustration of an audio speaker. Audio Software icon An illustration of a 3.5"" floppy disk. Software Images icon An illustration of two photographs. Images Donate icon An illustration of a heart shape Donate Ellipses icon An illustration of text ellipses. More"

div,overflow-clip closed style-scope media-slider,,

div,information-menu closed style-scope media-slider,,

div,info-box style-scope media-slider,,

div,search-menu tx-slide closed style-scope search-menu,,Search Metadata Search text contents Search TV news captions Search archived websites Advanced Search

div,no-script-message,,"The Wayback Machine requires your browser to support JavaScript, please email info@archive.org if you have any questions about this."

div,,footerHome,"The Wayback Machine is an initiative of the Internet Archive , a 501(c)(3) non-profit, building a digital library of Internet sites and other cultural artifacts in digital form. Other projects include Open Library & archive-it.org . Your use of the Wayback Machine is subject to the Internet Archive's Terms of Use ."
